name: Remote.it RDP Tunnel

on:
  workflow_dispatch:

jobs:
  rdp:
    runs-on: windows-latest

    steps:
    - name: Install Remote.it CLI
      run: |
        Invoke-WebRequest https://downloads.remote.it/cli/remoteit-windows.zip -OutFile remoteit.zip
        Expand-Archive remoteit.zip -DestinationPath .
        Move-Item .\remoteit\remoteit.exe .\remoteit.exe
      shell: powershell

    - name: Login to Remote.it
      run: .\remoteit.exe login --apikey $Env:REMOTEIT_KEY
      env:
        REMOTEIT_KEY: ${{ secrets.REMOTEIT_KEY }}
      shell: powershell

    - name: Enable RDP and Set Password
      run: |
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -Name "fDenyTSConnections" -Value 0
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -Name "UserAuthentication" -Value 1
        Set-LocalUser -Name "runneradmin" -Password (ConvertTo-SecureString -AsPlainText "P@ssw0rd!" -Force)
      shell: powershell

    - name: Share Port 3389 (RDP)
      run: .\remoteit.exe add --name "GitHub-RDP" --port 3389
      shell: powershell

    - name: Workflow Complete
      run: Write-Host "RDP is now exposed via Remote.it. Connect from your app using the device named 'GitHub-RDP'"
      shell: powershell
